// 99 Asmaul Husna - Nama-nama Allah Yang Indah
window.ASMAUL_HUSNA = [
  {no: 1, arabic: "الرَّحْمَنُ", latin: "Ar-Rahman", arti: "Yang Maha Pengasih", keutamaan: "Membaca nama ini 100x setelah sholat Subuh akan mendapat rahmat Allah"},
  {no: 2, arabic: "الرَّحِيمُ", latin: "Ar-Rahim", arti: "Yang Maha Penyayang", keutamaan: "Membaca 100x akan mendapat kasih sayang Allah"},
  {no: 3, arabic: "الْمَلِكُ", latin: "Al-Malik", arti: "Yang Maha Merajai", keutamaan: "Membaca 116x akan dimudahkan segala urusan"},
  {no: 4, arabic: "الْقُدُّوسُ", latin: "Al-Quddus", arti: "Yang Maha Suci", keutamaan: "Membaca 100x akan bersih dari dosa"},
  {no: 5, arabic: "السَّلاَمُ", latin: "As-Salam", arti: "Yang Maha Memberi Kesejahteraan", keutamaan: "Membaca 160x akan selamat dari bencana"},
  {no: 6, arabic: "الْمُؤْمِنُ", latin: "Al-Mu'min", arti: "Yang Maha Memberi Keamanan", keutamaan: "Membaca 136x akan aman dari segala bahaya"},
  {no: 7, arabic: "الْمُهَيْمِنُ", latin: "Al-Muhaimin", arti: "Yang Maha Pemelihara", keutamaan: "Membaca 145x akan dipelihara Allah"},
  {no: 8, arabic: "الْعَزِيزُ", latin: "Al-Aziz", arti: "Yang Maha Perkasa", keutamaan: "Membaca 94x akan mendapat kekuatan"},
  {no: 9, arabic: "الْجَبَّارُ", latin: "Al-Jabbar", arti: "Yang Maha Memaksa", keutamaan: "Membaca 206x akan dikabulkan hajatnya"},
  {no: 10, arabic: "الْمُتَكَبِّرُ", latin: "Al-Mutakabbir", arti: "Yang Maha Megah", keutamaan: "Membaca 662x akan dimuliakan"},
  {no: 11, arabic: "الْخَالِقُ", latin: "Al-Khaliq", arti: "Yang Maha Pencipta", keutamaan: "Membaca 731x akan dimudahkan rezeki"},
  {no: 12, arabic: "الْبَارِئُ", latin: "Al-Bari'", arti: "Yang Maha Melepaskan", keutamaan: "Membaca 203x akan lepas dari kesulitan"},
  {no: 13, arabic: "الْمُصَوِّرُ", latin: "Al-Mushawwir", arti: "Yang Maha Membentuk Rupa", keutamaan: "Membaca 336x istri mudah melahirkan"},
  {no: 14, arabic: "الْغَفَّارُ", latin: "Al-Ghaffar", arti: "Yang Maha Pengampun", keutamaan: "Membaca 1281x akan diampuni dosanya"},
  {no: 15, arabic: "الْقَهَّارُ", latin: "Al-Qahhar", arti: "Yang Maha Memaksa", keutamaan: "Membaca 306x akan menang atas musuh"},
  {no: 16, arabic: "الْوَهَّابُ", latin: "Al-Wahhab", arti: "Yang Maha Pemberi Karunia", keutamaan: "Membaca 14x akan dikabulkan hajatnya"},
  {no: 17, arabic: "الرَّزَّاقُ", latin: "Ar-Razzaq", arti: "Yang Maha Pemberi Rezeki", keutamaan: "Membaca 308x akan dilapangkan rezeki"},
  {no: 18, arabic: "الْفَتَّاحُ", latin: "Al-Fattah", arti: "Yang Maha Pembuka", keutamaan: "Membaca 489x akan dibukakan pintu rezeki"},
  {no: 19, arabic: "اَلْعَلِيْمُ", latin: "Al-'Alim", arti: "Yang Maha Mengetahui", keutamaan: "Membaca 150x akan bertambah ilmunya"},
  {no: 20, arabic: "الْقَابِضُ", latin: "Al-Qabidh", arti: "Yang Maha Menyempitkan", keutamaan: "Membaca 132x akan dikabulkan hajatnya"},
  {no: 21, arabic: "الْبَاسِطُ", latin: "Al-Basith", arti: "Yang Maha Melapangkan", keutamaan: "Membaca 72x akan dilapangkan rezeki"},
  {no: 22, arabic: "الْخَافِضُ", latin: "Al-Khafidh", arti: "Yang Maha Merendahkan", keutamaan: "Membaca 1020x akan direndahkan musuhnya"},
  {no: 23, arabic: "الرَّافِعُ", latin: "Ar-Rafi'", arti: "Yang Maha Meninggikan", keutamaan: "Membaca 351x akan ditinggikan derajatnya"},
  {no: 24, arabic: "الْمُعِزُّ", latin: "Al-Mu'izz", arti: "Yang Maha Memuliakan", keutamaan: "Membaca 117x akan dimuliakan"},
  {no: 25, arabic: "المُذِلُّ", latin: "Al-Mudzill", arti: "Yang Maha Menghinakan", keutamaan: "Membaca 770x akan dihinakan musuhnya"},
  {no: 26, arabic: "السَّمِيعُ", latin: "As-Sami'", arti: "Yang Maha Mendengar", keutamaan: "Membaca 180x akan dikabulkan doanya"},
  {no: 27, arabic: "الْبَصِيرُ", latin: "Al-Bashir", arti: "Yang Maha Melihat", keutamaan: "Membaca 302x akan terang hatinya"},
  {no: 28, arabic: "الْحَكَمُ", latin: "Al-Hakam", arti: "Yang Maha Menetapkan", keutamaan: "Membaca 68x akan menang dalam perkara"},
  {no: 29, arabic: "الْعَدْلُ", latin: "Al-'Adl", arti: "Yang Maha Adil", keutamaan: "Membaca 104x akan berlaku adil"},
  {no: 30, arabic: "اللَّطِيفُ", latin: "Al-Lathif", arti: "Yang Maha Lembut", keutamaan: "Membaca 129x akan dimudahkan urusannya"},
  {no: 31, arabic: "الْخَبِيرُ", latin: "Al-Khabir", arti: "Yang Maha Mengetahui", keutamaan: "Membaca 812x akan tahu rahasia"},
  {no: 32, arabic: "الْحَلِيمُ", latin: "Al-Halim", arti: "Yang Maha Penyantun", keutamaan: "Membaca 88x akan sabar menghadapi cobaan"},
  {no: 33, arabic: "الْعَظِيمُ", latin: "Al-'Azhim", arti: "Yang Maha Agung", keutamaan: "Membaca 1020x akan diagungkan"},
  {no: 34, arabic: "الْغَفُورُ", latin: "Al-Ghafur", arti: "Yang Maha Pengampun", keutamaan: "Membaca 1286x akan diampuni dosanya"},
  {no: 35, arabic: "الشَّكُورُ", latin: "Asy-Syakur", arti: "Yang Maha Pembalas Budi", keutamaan: "Membaca 526x akan bersyukur"},
  {no: 36, arabic: "الْعَلِيُّ", latin: "Al-'Aliy", arti: "Yang Maha Tinggi", keutamaan: "Membaca 110x akan ditinggikan derajatnya"},
  {no: 37, arabic: "الْكَبِيرُ", latin: "Al-Kabir", arti: "Yang Maha Besar", keutamaan: "Membaca 232x akan diagungkan"},
  {no: 38, arabic: "الْحَفِيظُ", latin: "Al-Hafizh", arti: "Yang Maha Memelihara", keutamaan: "Membaca 998x akan dipelihara"},
  {no: 39, arabic: "المُقيِت", latin: "Al-Muqit", arti: "Yang Maha Pemberi Kecukupan", keutamaan: "Membaca 550x akan dicukupi kebutuhannya"},
  {no: 40, arabic: "الْحسِيبُ", latin: "Al-Hasib", arti: "Yang Maha Membuat Perhitungan", keutamaan: "Membaca 80x akan dimudahkan perhitungannya"},
  {no: 41, arabic: "الْجَلِيلُ", latin: "Al-Jalil", arti: "Yang Maha Mulia", keutamaan: "Membaca 73x akan dimuliakan"},
  {no: 42, arabic: "الْكَرِيمُ", latin: "Al-Karim", arti: "Yang Maha Pemurah", keutamaan: "Membaca 270x akan dimurahkan rezeki"},
  {no: 43, arabic: "الرَّقِيبُ", latin: "Ar-Raqib", arti: "Yang Maha Mengawasi", keutamaan: "Membaca 312x akan dijaga dari maksiat"},
  {no: 44, arabic: "الْمُجِيبُ", latin: "Al-Mujib", arti: "Yang Maha Mengabulkan", keutamaan: "Membaca 55x akan dikabulkan doanya"},
  {no: 45, arabic: "الْوَاسِعُ", latin: "Al-Wasi'", arti: "Yang Maha Luas", keutamaan: "Membaca 137x akan dilapangkan rezeki"},
  {no: 46, arabic: "الْحَكِيمُ", latin: "Al-Hakim", arti: "Yang Maha Bijaksana", keutamaan: "Membaca 78x akan bijaksana"},
  {no: 47, arabic: "الْوَدُودُ", latin: "Al-Wadud", arti: "Yang Maha Pencinta", keutamaan: "Membaca 20x akan dicintai orang"},
  {no: 48, arabic: "الْمَجِيدُ", latin: "Al-Majid", arti: "Yang Maha Mulia", keutamaan: "Membaca 57x akan dimuliakan"},
  {no: 49, arabic: "الْبَاعِثُ", latin: "Al-Ba'its", arti: "Yang Maha Membangkitkan", keutamaan: "Membaca 573x akan dibangkitkan dari kesulitan"},
  {no: 50, arabic: "الشَّهِيدُ", latin: "Asy-Syahid", arti: "Yang Maha Menyaksikan", keutamaan: "Membaca 319x akan disaksikan amal baiknya"},
  {no: 51, arabic: "الْحَقُّ", latin: "Al-Haqq", arti: "Yang Maha Benar", keutamaan: "Membaca 108x akan menang dalam perkara"},
  {no: 52, arabic: "الْوَكِيلُ", latin: "Al-Wakil", arti: "Yang Maha Memelihara", keutamaan: "Membaca 66x akan dipelihara Allah"},
  {no: 53, arabic: "الْقَوِيُّ", latin: "Al-Qawiyy", arti: "Yang Maha Kuat", keutamaan: "Membaca 116x akan kuat imannya"},
  {no: 54, arabic: "الْمَتِينُ", latin: "Al-Matin", arti: "Yang Maha Kokoh", keutamaan: "Membaca 500x akan kokoh imannya"},
  {no: 55, arabic: "الْوَلِيُّ", latin: "Al-Waliyy", arti: "Yang Maha Melindungi", keutamaan: "Membaca 46x akan dilindungi Allah"},
  {no: 56, arabic: "الْحَمِيدُ", latin: "Al-Hamid", arti: "Yang Maha Terpuji", keutamaan: "Membaca 62x akan dipuji orang"},
  {no: 57, arabic: "الْمُحْصِي", latin: "Al-Muhshi", arti: "Yang Maha Menghitung", keutamaan: "Membaca 148x akan dihitung amal baiknya"},
  {no: 58, arabic: "الْمُبْدِئُ", latin: "Al-Mubdi'", arti: "Yang Maha Memulai", keutamaan: "Membaca 56x akan dimudahkan memulai usaha"},
  {no: 59, arabic: "الْمُعِيدُ", latin: "Al-Mu'id", arti: "Yang Maha Mengembalikan", keutamaan: "Membaca 124x akan dikembalikan yang hilang"},
  {no: 60, arabic: "الْمُحْيِي", latin: "Al-Muhyi", arti: "Yang Maha Menghidupkan", keutamaan: "Membaca 68x akan hidup hatinya"},
  {no: 61, arabic: "اَلْمُمِيتُ", latin: "Al-Mumit", arti: "Yang Maha Mematikan", keutamaan: "Membaca 490x akan mati hawa nafsunya"},
  {no: 62, arabic: "الْحَيُّ", latin: "Al-Hayy", arti: "Yang Maha Hidup", keutamaan: "Membaca 18x akan panjang umur"},
  {no: 63, arabic: "الْقَيُّومُ", latin: "Al-Qayyum", arti: "Yang Maha Berdiri Sendiri", keutamaan: "Membaca 156x akan kuat imannya"},
  {no: 64, arabic: "الْوَاجِدُ", latin: "Al-Wajid", arti: "Yang Maha Penemu", keutamaan: "Membaca 14x akan menemukan yang dicari"},
  {no: 65, arabic: "الْمَاجِدُ", latin: "Al-Majid", arti: "Yang Maha Mulia", keutamaan: "Membaca 48x akan dimuliakan"},
  {no: 66, arabic: "الْواحِدُ", latin: "Al-Wahid", arti: "Yang Maha Tunggal", keutamaan: "Membaca 19x akan dimudahkan jodoh"},
  {no: 67, arabic: "اَلاَحَدُ", latin: "Al-Ahad", arti: "Yang Maha Esa", keutamaan: "Membaca 13x akan dicintai orang"},
  {no: 68, arabic: "الصَّمَدُ", latin: "Ash-Shamad", arti: "Yang Maha Dibutuhkan", keutamaan: "Membaca 134x akan dicukupi kebutuhannya"},
  {no: 69, arabic: "الْقَادِرُ", latin: "Al-Qadir", arti: "Yang Maha Menentukan", keutamaan: "Membaca 305x akan dikabulkan hajatnya"},
  {no: 70, arabic: "الْمُقْتَدِرُ", latin: "Al-Muqtadir", arti: "Yang Maha Berkuasa", keutamaan: "Membaca 744x akan menang atas musuh"},
  {no: 71, arabic: "الْمُقَدِّمُ", latin: "Al-Muqaddim", arti: "Yang Maha Mendahulukan", keutamaan: "Membaca 184x akan didahulukan urusannya"},
  {no: 72, arabic: "الْمُؤَخِّرُ", latin: "Al-Mu'akhkhir", arti: "Yang Maha Mengakhirkan", keutamaan: "Membaca 846x akan diakhirkan musuhnya"},
  {no: 73, arabic: "الأوَّلُ", latin: "Al-Awwal", arti: "Yang Maha Awal", keutamaan: "Membaca 37x akan dimudahkan segala urusan"},
  {no: 74, arabic: "الآخِرُ", latin: "Al-Akhir", arti: "Yang Maha Akhir", keutamaan: "Membaca 801x akan baik akhir hidupnya"},
  {no: 75, arabic: "الظَّاهِرُ", latin: "Azh-Zhahir", arti: "Yang Maha Nyata", keutamaan: "Membaca 1106x akan terang hatinya"},
  {no: 76, arabic: "الْبَاطِنُ", latin: "Al-Bathin", arti: "Yang Maha Ghaib", keutamaan: "Membaca 62x akan tahu rahasia"},
  {no: 77, arabic: "الْوَالِي", latin: "Al-Wali", arti: "Yang Maha Memerintah", keutamaan: "Membaca 46x akan jadi pemimpin"},
  {no: 78, arabic: "الْمُتَعَالِي", latin: "Al-Muta'ali", arti: "Yang Maha Tinggi", keutamaan: "Membaca 470x akan ditinggikan derajatnya"},
  {no: 79, arabic: "الْبَرُّ", latin: "Al-Barr", arti: "Yang Maha Penderma", keutamaan: "Membaca 202x akan dermawan"},
  {no: 80, arabic: "التَّوَابُ", latin: "At-Tawwab", arti: "Yang Maha Penerima Taubat", keutamaan: "Membaca 409x akan diterima taubatnya"},
  {no: 81, arabic: "الْمُنْتَقِمُ", latin: "Al-Muntaqim", arti: "Yang Maha Pemberi Balasan", keutamaan: "Membaca 630x akan dibalas musuhnya"},
  {no: 82, arabic: "العَفُوُّ", latin: "Al-'Afuww", arti: "Yang Maha Pemaaf", keutamaan: "Membaca 156x akan dimaafkan dosanya"},
  {no: 83, arabic: "الرَّؤُوفُ", latin: "Ar-Ra'uf", arti: "Yang Maha Pengasih", keutamaan: "Membaca 287x akan dikasihani Allah"},
  {no: 84, arabic: "مَالِكُ الْمُلْكِ", latin: "Malik-ul-Mulk", arti: "Yang Maha Penguasa Kerajaan", keutamaan: "Membaca 212x akan jadi pemimpin"},
  {no: 85, arabic: "ذُوالْجَلاَلِ وَالإكْرَامِ", latin: "Dzul-Jalali wal-Ikram", arti: "Yang Mempunyai Kebesaran dan Kemuliaan", keutamaan: "Membaca 100x akan dimuliakan"},
  {no: 86, arabic: "الْمُقْسِطُ", latin: "Al-Muqsith", arti: "Yang Maha Adil", keutamaan: "Membaca 209x akan berlaku adil"},
  {no: 87, arabic: "الْجَامِعُ", latin: "Al-Jami'", arti: "Yang Maha Mengumpulkan", keutamaan: "Membaca 114x akan dikumpulkan keluarganya"},
  {no: 88, arabic: "الْغَنِيُّ", latin: "Al-Ghaniyy", arti: "Yang Maha Kaya", keutamaan: "Membaca 1060x akan kaya"},
  {no: 89, arabic: "الْمُغْنِي", latin: "Al-Mughni", arti: "Yang Maha Memberi Kekayaan", keutamaan: "Membaca 1140x akan dikayakan"},
  {no: 90, arabic: "اَلْمَانِعُ", latin: "Al-Mani'", arti: "Yang Maha Mencegah", keutamaan: "Membaca 161x akan dicegah dari maksiat"},
  {no: 91, arabic: "الضَّارَّ", latin: "Adh-Dharr", arti: "Yang Maha Penimpa Kemudharatan", keutamaan: "Membaca 1001x akan selamat dari bahaya"},
  {no: 92, arabic: "النَّافِعُ", latin: "An-Nafi'", arti: "Yang Maha Memberi Manfaat", keutamaan: "Membaca 201x akan bermanfaat hidupnya"},
  {no: 93, arabic: "النُّورُ", latin: "An-Nur", arti: "Yang Maha Bercahaya", keutamaan: "Membaca 256x akan terang hatinya"},
  {no: 94, arabic: "الْهَادِي", latin: "Al-Hadi", arti: "Yang Maha Pemberi Petunjuk", keutamaan: "Membaca 20x akan mendapat hidayah"},
  {no: 95, arabic: "الْبَدِيعُ", latin: "Al-Badi'", arti: "Yang Maha Pencipta", keutamaan: "Membaca 86x akan kreatif"},
  {no: 96, arabic: "اَلْبَاقِي", latin: "Al-Baqi", arti: "Yang Maha Kekal", keutamaan: "Membaca 113x akan kekal amal baiknya"},
  {no: 97, arabic: "الْوَارِثُ", latin: "Al-Warits", arti: "Yang Maha Pewaris", keutamaan: "Membaca 707x akan dapat warisan"},
  {no: 98, arabic: "الرَّشِيدُ", latin: "Ar-Rasyid", arti: "Yang Maha Pandai", keutamaan: "Membaca 514x akan pandai"},
  {no: 99, arabic: "الصَّبُورُ", latin: "Ash-Shabur", arti: "Yang Maha Sabar", keutamaan: "Membaca 298x akan sabar menghadapi cobaan"}
];
